In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
                [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a Dataframe from a numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Numpy arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2, 3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_Array = np.arange(0, 10, 2)
range_Array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[3, 7, 5, 3, 5],
       [7, 8, 3, 4, 6],
       [0, 9, 5, 0, 4]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [30]:
random_Array2 = np.random.random((5, 3))
random_Array2

array([[0.588007  , 0.00789039, 0.85206301],
       [0.91266961, 0.23719686, 0.34907042],
       [0.19601648, 0.74967186, 0.33850165],
       [0.07945471, 0.75121266, 0.56705407],
       [0.40645825, 0.17498098, 0.30785207]])

In [31]:
random_Array2.shape

(5, 3)

In [32]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.11661768, 0.97837218, 0.86443373],
       [0.4273761 , 0.82876015, 0.33393489],
       [0.58330506, 0.41431902, 0.60134677],
       [0.78392326, 0.82659036, 0.83215182],
       [0.41759157, 0.73046781, 0.76785467]])

In [36]:
# Pseudo-random numbers
np.random.seed(seed=0) # it is used to make the random numbers constant
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [40]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [41]:
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and Matrices

In [42]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a1

array([1, 2, 3])

In [44]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [45]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
a1[0]

1

In [47]:
a2[0]

array([1. , 2. , 3.3])

In [48]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [50]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [51]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [52]:
# get the first 4 numbers of the inner most arrays
a4[:,:,:,:4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

In [53]:
a4[:,:,:,:1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

## Manipulating & comparing arrays

### Arithmetic

In [54]:
a1

array([1, 2, 3])

In [55]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [56]:
a1 + ones

array([2., 3., 4.])

In [57]:
a1 - ones

array([0., 1., 2.])

In [58]:
a1 * ones

array([1., 2., 3.])

In [59]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [60]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [61]:
a1 / ones

array([1., 2., 3.])

In [62]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [64]:
# Floor dividions removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [65]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [66]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [67]:
np.add(a1, ones)

array([2., 3., 4.])

In [68]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [69]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [70]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [71]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [72]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [73]:
sum(listy_list)

6

In [74]:
np.sum(a1)

6

Use python's methods(`sum()`) on Python datatypes and use Numpy's methods on Numpy arrays(`np.sum()`).

In [76]:
# create a massive Numpy array

massive_array = np.random.random(10000)
massive_array.size

10000

In [77]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [78]:
%timeit sum(massive_array) #pythons sum()
%timeit np.sum(massive_array) # Numpys sum()

932 µs ± 74.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
11.3 µs ± 754 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [79]:
np.mean(a2)

3.6333333333333333

In [80]:
np.max(a2)

6.5

In [81]:
np.min(a2)

1.0

In [82]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [83]:
# vsrisnce  = measure of the average degree to which each number is diffrent to the mean
# Higher variance = Wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [84]:
# Standard deviation = aquareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422